import { posters } from './../../../assets/posters';

export const STAR_WARS_EPISODES = [
  {
    number: 1,
    title: 'The Phantom Menace',
    to: '/movies/episode-1',
    slug: 'episode-1',
    imdb: 'tt0120915',
    poster: posters.episode_1,
    spotifyId: '45EFycwtfRhnDPWbc2mClK',
  },
  {
    number: 2,
    title: 'The Attack of the Clones',
    to: '/movies/episode-2',
    slug: 'episode-2',
    imdb: 'tt0121765',
    poster: posters.episode_2,
    spotifyId: '4RSVY5851aNeCttrDpdj7A',
  },
  {
    number: 3,
    title: 'Revenge of the Sith',
    to: '/movies/episode-3',
    slug: 'episode-3',
    imdb: 'tt0121766',
    poster: posters.episode_3,
    spotifyId: '6zhlos3HFJrWni7rjqxacg',
  },
  {
    number: 4,
    title: 'A New Hope',
    to: '/movies/episode-4',
    slug: 'episode-4',
    imdb: 'tt0076759',
    poster: posters.episode_4,
    spotifyId: '55gMu4AvAKCbCaGv3GIXgy',
  },
  {
    number: 5,
    title: 'The Empire Strikes Back',
    to: '/movies/episode-5',
    slug: 'episode-5',
    imdb: 'tt0080684',
    poster: posters.episode_5,
    spotifyId: '44TnXcUjTIHPBBROepl99a',
  },
  {
    number: 6,
    title: 'The Return of the Jedi',
    to: '/movies/episode-6',
    slug: 'episode-6',
    imdb: 'tt0086190',
    poster: posters.episode_6,
    spotifyId: '1gt4PAxdMmq5DUV7tyuNxx',
  },
  {
    number: 7,
    title: 'The Force Awakens',
    to: '/movies/episode-7',
    slug: 'episode-7',
    imdb: 'tt2488496',
    poster: posters.episode_7,
    spotifyId: '3fUKGTsiYL1kSroBWBLmmR',
  },
  {
    number: 8,
    title: 'The Last Jedi',
    to: '/movies/episode-8',
    slug: 'episode-8',
    imdb: 'tt2527336',
    poster: posters.episode_8,
    spotifyId: '0LhcWlgnpCVHqOVFZFuoPX',
  },
];
